version: '3'

services:
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: rvillage/ruby2.4.1-alpine_rails
    environment:
      DATABASE_USER: postgres
      DATABASE_PASS: password
      DATABASE_HOST: postgres
    ports:
      - '3000:3000'
    networks:
      - default
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - bundle_data:/usr/local/bundle
    command: ["bundle", "exec", "rails", "s"]

volumes:
  postgres_data:
  bundle_data:
